feat: informative error when passing string as pat (#204)
# The problem

Currently, to use `GithubImport` you need to use:

```python
THIS_IMPORT = sdk.GithubImport(
    "git@github.com:zapatacomputing/chem_demo.git",
    git_ref="zaptim/devremote",
    personal_access_token=sdk.Secret(name="GITHUBPAT"),
)
```

Many users pass the secret name directly, bypassing sdk.Secret(...).

```python
_ = sdk.GithubImport(
    ...
    personal_access_token="GITHUBPAT",
)
```

It leads to unhandled exceptions with a trace back that's not very
helpful.

```
...
    import_models_dict[imp] = _make_import_model(imp)
  File "/usr/local/lib/python3.9/site-packages/orquestra/sdk/_base/_traversal.py", line 403, in _make_import_model
    secret_name=imp.auth_secret.name,
AttributeError: 'str' object has no attribute 'name'
```

# This PR's solution

`GitHubImport` now checks for `personal_access_token` values that are
not instances of `sdk.Secret`, raising a TypeError. For the example
above, the error now reads:

```
Traceback (most recent call last):
...
TypeError: You passed a string as `personal_access_token = "..."`. Please pass `personal_access_token = sdk.Secret(name="...")` instead. It might seem verbose, but it's a precaution against committing plain-text credentials to your git repo, or leaking secret values as part of the workflow definition.
Suggested fix:
  personal_access_token = sdk.Secret(name="GITHUBPAT")
```

I also added a more generic version for types that are neither string
nor Secret in order to make sure that we strictly enforce Secret only
without assuming that the incorrect value is a str (covering, for
example, a user pasting a numeric-only PAT without enclosing it in
quotes).


# Checklist

_Check that this PR satisfies the following items:_

- [X] Tests have been added for new features/changed behavior (if no new
features have been added, check the box).
- [X] The [changelog file](CHANGELOG.md) has been updated with a
user-readable description of the changes (if the change isn't visible to
the user in any way, check the box).
- [X] The PR's title is prefixed with
`<feat/fix/chore/imp[rovement]/int[ernal]/docs>[!]:`
- [X] The PR is linked to a JIRA ticket (if there's no suitable ticket,
check the box).


[ORQSDK-861](https://zapatacomputing.atlassian.net/browse/ORQSDK-861?atlOrigin=eyJpIjoiNDcyZjE2MzNjMWMwNGIzOTgzNzEzMzlhMWMxZTY4YzUiLCJwIjoiaiJ9)

[ORQSDK-861]:
https://zapatacomputing.atlassian.net/browse/ORQSDK-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ