feat: catch exceptions from environment setup in workflow driver ray (#301)
# The problem

Problems that prevent the environment being set up correctly get
reported to the user by Ray with a Wall Of Text (tm) on ray local, and
with a silent failure on ray remote. Ideally we would want to catch and
handle these exceptions so we can present them in a more user-friendly
and consistent way.

Example (caused by a python dependency clash):

```python
import orquestra.sdk as sdk

@sdk.task(
    source_import=sdk.InlineImport(),
    dependency_imports=sdk.PythonImports("MarkupSafe==1.0.0", "Jinja2==2.7.2")
)
def cause_env_setup_failure_task():
    pass

@sdk.workflow
def cause_env_setup_failure():
    return [cause_env_setup_failure_task()]

workflow_run = cause_env_setup_failure().run("ray")
workflow_run.wait_until_finished()
```
produces the following output:
```
wf.cause_env_setup_failure.769b6da is RUNNING. Sleeping for 4.0s...
Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkflowManagementActor.execute_workflow() (pid=70432, ip=127.0.0.1, actor_id=e54d38692951e81b4db81eeb01000000, repr=<ray.workflow.workflow_access.WorkflowManagementActor object at 0x108ac1fc0>)
ray.exceptions.RuntimeEnvSetupError: Failed to set up runtime environment.
ray::WorkflowManagementActor.execute_workflow() (pid=70432, ip=127.0.0.1, actor_id=e54d38692951e81b4db81eeb01000000, repr=<ray.workflow.workflow_access.WorkflowManagementActor object at 0x108ac1fc0>)
  File "/Users/benjaminmummery/Documents/Projects/orquestra-workflow-sdk/venv/lib/python3.10/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 351, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/benjaminmummery/Documents/Projects/orquestra-workflow-sdk/venv/lib/python3.10/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 311, in _setup_runtime_env
    await create_for_plugin_if_needed(
ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[9] failed with the following details.
Command '['/Users/benjaminmummery/.orquestra/ray/session_2023-08-22_15-46-52_786640_70402/runtime_resources/pip/fbec108193f1098c87f3b27d46a54cde32a4ca85/virtualenv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--no-cache-dir', '-r', '/Users/benjaminmummery/.orquestra/ray/session_2023-08-22_15-46-52_786640_70402/runtime_resources/pip/fbec108193f1098c87f3b27d46a54cde32a4ca85/requirements.txt']' returned non-zero exit status 1.
Last 50 lines of stdout:
    Collecting MarkupSafe==1.0.0
      Downloading MarkupSafe-1.0.tar.gz (14 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
      error: subprocess-exited-with-error
  
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [6 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/private/var/folders/_t/056rm7ns1kj80m2fwgc9z51h0000gn/T/pip-install-edfm9ey4/markupsafe_dd526c70a51a48e297f0b8ed8db93e1c/setup.py", line 6, in <module>
              from setuptools import setup, Extension, Feature
          ImportError: cannot import name 'Feature' from 'setuptools' (/Users/benjaminmummery/.orquestra/ray/session_2023-08-22_15-46-52_786640_70402/runtime_resources/pip/fbec108193f1098c87f3b27d46a54cde32a4ca85/virtualenv/lib/python3.10/site-packages/setuptools/__init__.py)
          [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.


The above exception was the direct cause of the following exception:

ray::WorkflowManagementActor.execute_workflow() (pid=70432, ip=127.0.0.1, actor_id=e54d38692951e81b4db81eeb01000000, repr=<ray.workflow.workflow_access.WorkflowManagementActor object at 0x108ac1fc0>)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/benjaminmummery/Documents/Projects/orquestra-workflow-sdk/venv/lib/python3.10/site-packages/ray/workflow/workflow_access.py", line 209, in execute_workflow
    await executor.run_until_complete(job_id, context, wf_store)
  File "/Users/benjaminmummery/Documents/Projects/orquestra-workflow-sdk/venv/lib/python3.10/site-packages/ray/workflow/workflow_executor.py", line 109, in run_until_complete
    await asyncio.gather(
  File "/Users/benjaminmummery/Documents/Projects/orquestra-workflow-sdk/venv/lib/python3.10/site-packages/ray/workflow/workflow_executor.py", line 356, in _handle_ready_task
    raise err
ray.workflow.exceptions.WorkflowExecutionError: Workflow[id=wf.cause_env_setup_failure.769b6da] failed during execution.
wf.cause_env_setup_failure.769b6da is FAILED
```

# This PR's solution

- Adds a message field to `WorkflowRun` (Mirroring the one we already
had in TaskRun).
- When the dag `get_workflow_run_status` encounters a failed state, it
checks the env logs for lines indicating a failure to setup the
environment and sets the message accordingly. If the failure is not due
to the env setup failing, the message simply directs the user to consult
the logs.
- When the status of a completed workflow run is displayed to the user
in `wait_until_finished()`, the message is included (if there is one).

The practical upshot of this is that the example above becomes:

```
wf.cause_env_setup_failure.769b6da is RUNNING. Sleeping for 4.0s...
wf.cause_env_setup_failure.769b6da is FAILED - Could not set up runtime environment. See environment setup logs for details. `orq wf logs wf.cause_env_setup_failure.769b6da --env-setup`
```
and a workflow that fails for any other reason produces:

```
wf.some_other_wf.769b6da is RUNNING. Sleeping for 4.0s...
wf.some_other_wf.769b6da is FAILED - The workflow encountered an issue. Please consult the logs for more information. `orq wf logs wf.cause_env_setup_failure.769b6das`
```

- Also adds logic to handle trying to determine the wf end time from
task end times in cases where no tasks have started.

# Considerations

- There is an existing exception in Ray,
`ray.exceptions.RuntimeEnvSetupError`, that is supposed to be raised in
this case. It appears that this works with Ray primitives, but not with
workflows. Should we ever transition from using workflows to using
primitives, we can likely make use of that exception rather than parsing
the logs.
- While not _raised_, `RuntimeEnvSetupError`is written to the logs, but
only on CE. Therefore, on ray local we actually see the `The workflow
encountered an issue...` message instead of the env setup one.

# Abandoned Routes

- Catching the exception
- Ray doesn't raise it, it gets printed to stdout only if the submitting
process persists. We can't rely on it being visible.
- Changing our code so that the exception is raised in a way we can
catch
- The only change we can see that would achieve this is switching from
workflows to primitives, which is OOS for this PR.
- Using the log line "Runtime env creation failed for * times, don't
retry any more"
- This _is_ a reliable indicator of an env-setup error, but it is
written to the `env_setup_agent.log` file. We cannot include this file
in fluentbit as it may contain secrets.

# Checklist

_Check that this PR satisfies the following items:_

- [X] Tests have been added for new features/changed behavior (if no new
features have been added, check the box).
- [ ] The [changelog file](CHANGELOG.md) has been updated with a
user-readable description of the changes (if the change isn't visible to
the user in any way, check the box).
- [X] The PR's title is prefixed with
`<feat/fix/chore/imp[rovement]/int[ernal]/docs>[!]:`
- [X] The PR is linked to a JIRA ticket (if there's no suitable ticket,
check the box).

[ORQSDK-939] 

[ORQSDK-939]:
https://zapatacomputing.atlassian.net/browse/ORQSDK-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---------

Co-authored-by: Alexander Juda <6004040+alexjuda@users.noreply.github.com>